chore: Fix gitea url in workflows

diff --git a/.gitea/workflows/versioning.yml b/.gitea/workflows/versioning.yml
--- a/.gitea/workflows/versioning.yml
+++ b/.gitea/workflows/versioning.yml
@@ -117,6 +117,12 @@ jobs:
           git add pubspec.yaml CHANGELOG.md
           git commit -m "chore: bump version to $NEW_VERSION+$NEW_BUILD and update changelog"
           
+          # Vérification de l'URL du dépôt
+          if [ -z "${{ secrets.GITEA_URL }}" ]; then
+            echo "❌ ERROR: GITEA_URL is not set!"
+            exit 1
+          fi
+
           GITEA_URL="${{ secrets.GITEA_URL }}"
           GITEA_REPO="mobiles/flutter-mobile.git"
           FULL_REPO_URL="${GITEA_URL}/${GITEA_REPO}"
